kind: pipeline
type: vm
name: testing

platform:
  os: linux
  arch: amd64

pool:
  use: ubuntu

steps:
  - name: test
    image: golang:1.19
    commands:
      - go test -cover ./...

---
kind: pipeline
type: vm
name: linux-amd64

platform:
  os: linux
  arch: amd64

pool:
  use: ubuntu

steps:
  - name: build
    image: golang:1.16
    commands:
      - sh scripts/build.sh
  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: drone/drone-runner-kube
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.linux.amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

depends_on:
  - testing
  
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: vm
name: linux-arm64

platform:
  os: linux
  arch: arm64

pool:
  use: ubuntu_arm64

steps:
  - name: build
    image: golang:1.16
    commands:
      - sh scripts/build.sh
  - name: publish_arm64
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: drone/drone-runner-kube
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: docker/Dockerfile.linux.arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

depends_on:
  - testing

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: vm
name: manifest

platform:
  os: linux
  arch: amd64

pool:
  use: ubuntu
  
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      spec: docker/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username

depends_on:
  - linux-amd64
  - linux-arm64

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
